# Use postgres/example user/password credentials
version: '3.7'

services:
  postgres:
    image: postgres
    container_name: scrapbook_db_server
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: scrapbook
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  postgrest:
    image: postgrest/postgrest
    container_name: scrapbook_postgrest
    ports:
      - "3001:3000"
    links:
      - postgres:postgres
    environment:
      PGRST_DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/scrapbook
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: admin #In production this role should not be the same as the one used for the connection
    depends_on:
      - postgres
  adminer:
    image: adminer
    container_name: scrapbook_adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
  nginx:
    image: nginx
    container_name: scrapbook_nginx
    ports:
      - 80:80
    volumes:
      - nginx-static-serve:/usr/share/nginx/html
volumes:
  postgres-data:
  nginx-static-serve:
