# Use postgres/example user/password credentials
version: '3.7'

services:
  postgres:
    image: postgres
    container_name: db_server
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: scrapbook
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  postgrest:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    links:
      - postgres:postgres
    environment:
      PGRST_DB_URI: postgres://postgres:example@postgres:5432/scrapbook
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: postgres #In production this role should not be the same as the one used for the connection
    depends_on:
      - postgres
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
volumes:
  postgres-data: